export { default as Home } from './Home';
export { default as Posts } from './Posts';
export { default as Photos } from './Photos';
export { default as Users } from './Users';
export { default as User } from './User';
export { default as Counter } from './CounterPage';
export { default as About } from './About';
export { default as Post } from './Post';
export { default as PostsList } from './PostsList';